### ISSUE TITLE
multiple entities in one string

### ISSUE THREAD

**Issue by MaximKhasiev** [ZhengTang1120/entity_extraction#1]
Hello,

First of all, thank you for an amazing tool!

I am trying to use the entity extractor to extract brand names that are included in a dictionary from the list of different brands. It works perfectly till it comes to such brand names as "ING", or "MAN".

For example, 
"Bunnings" is extracted as both "Bunnings" and "ING"
and 
"National Storage Coca Cola Pepsi" becomes "National Storage", **"Ion"**, "Coca-Cola", and "Pepsi"

Meanwhile, deleting these names from the dictionary is not an option, because sometimes it is actually "Man", "Ion", and "ING".
is there a way to avoid that kind of mistakes?

Thank you!

**Comment by ZhengTang1120** [comment]
Hi,

I think one way to solve this is to check the candwins, it has start and end index. If the candidate window is inside a word in query string, you can discard it.

Best

**Comment by MaximKhasiev** [comment]
That's a good idea, thank you. :+1: Though, it is not really clear to me how can we determine if it is inside the word? I had a look at candwins and, tell me if I'm mistaken, it seems like end position is determined regardless of the spaces? so that if we have 3 brands listed in one cell (coca-cola tasmania pepsi) what would be the correct way to check that  "man" is inside "tasmania", but not a separate brand itself?
I am sorry if it is a silly question, I'm not coder myself and just trying to figure it out :)

**Comment by ZhengTang1120** [comment]
I think it's a good question. The end position has some problem, it's the end position of a bi-gram char, so end position+1 is the actual end char. So for checking if the candidate is inside the word or not, you can check the char in [start position - 1] and [end position + 2]. If they are both not spaces, it's inside a word. For your example, "s" and "i" is the chars in front and end of "man", so it's inside the word "tasmania".

**Comment by MaximKhasiev** [comment]
Thank you so much for helping on this! I got quite confused on the calculation of the positions. Thanks a lot! If you ever in Toronto - beer is on me ;)

**Comment by ZhengTang1120** [comment]
You are welcome. Let me know if you have any other questions.
